#!/bin/bash

###############################################################################
#
# ./hipchat_room_message
#
# A script for sending a system message to a room.
#
# Docs: http://github.com/hipchat/hipchat-cli
#
# Usage:
#   cat message.txt | ./hipchat_room_message -t <token> -r 1234 -f "System"
#   echo -e "New\nline" | ./hipchat_room_message -t <token> -r 1234 -f "System"
#
###############################################################################

# exit on failure
set -e

usage() {
  cat << EOF
Usage: $0 -t <token> -r <room id> -f <from name>

This script will read from stdin and send the contents to the given room as
a system message.

OPTIONS:
   -h             Show this message
   -t <token>     API token
   -r <room id>   Room ID
   -f <from name> From name
   -c <color>     Message color (yellow, red, green, purple, gray or random - default: yellow)
   -m <format>    Message format (html or text - default: html)
   -i <input>     Optional: Input to send to room (default: stdin)
   -l <level>     Nagios message level (critical, warning, unknown, ok, down, up). Will override color.
   -s <status>    Zabbix trigger status (PROBLEM, OK). Re-maps <level> (-l) to Zabbix trigger severity 
                  (Disaster, High, Average, Warning, Information, Not classified). Will override color.
   -n             Trigger notification for people in the room
   -o             API host (api.hipchat.com)
   -v <version>   API version (default: v1)
EOF
}

# Include hipchat defaults if available
test -f /etc/hipchat && . /etc/hipchat

TOKEN=${HIPCHAT_TOKEN:-}
ROOM_ID=${HIPCHAT_ROOM_ID:-}
FROM=${HIPCHAT_FROM:-}
COLOR=${HIPCHAT_COLOR:-yellow}
FORMAT=${HIPCHAT_FORMAT:-html}
MESSAGE=${HIPCHAT_MESSAGE:-html}
NOTIFY=${HIPCHAT_NOTIFY:-0}
HOST=${HIPCHAT_HOST:-api.hipchat.com}
LEVEL=${HIPCHAT_LEVEL:-}
STATUS=${HIPCHAT_STATUS:-}
API=${HIPCHAT_API:-v1}
while getopts “ht:r:f:c:m:o:i:l:s:v:n” OPTION; do
  case $OPTION in
    h) usage; exit 1;;
    t) TOKEN=$OPTARG;;
    r) ROOM_ID=$OPTARG;;
    f) FROM=$OPTARG;;
    c) COLOR=$OPTARG;;
    m) FORMAT=$OPTARG;;
    n) NOTIFY=1;;
    i) INPUT=$OPTARG;;
    l) LEVEL=$OPTARG;;
    s) STATUS=$OPTARG;;
    o) HOST=$OPTARG;;
    v) API=$OPTARG;;
    [?]) usage; exit;;
  esac
done

# check for required args
if [[ -z $TOKEN ]] || [[ -z $ROOM_ID ]] || [[ -z $FROM ]]; then
  usage
  exit 1
fi

# Override color based on level / status
if [ ! -z "$LEVEL" ]; then
  LEVEL=$(echo $LEVEL | tr '[:lower:]' '[:upper:]')

  if [ ! -z "$STATUS" ]; then
    # Map Level to zabbix trigger severity
    STATUS=$(echo $STATUS | tr '[:lower:]' '[:upper:]')
    if [[ "$STATUS" == 'OK' ]]; then
      COLOR="green";
    elif [[ $LEVEL == 'DISASTER' ]]; then
      COLOR="red";
    elif [[ $LEVEL == 'HIGH' ]]; then
      COLOR="red";
    elif [[ $LEVEL == 'AVERAGE' ]]; then
      COLOR="red";
    elif [[ $LEVEL == 'WARNING' ]]; then
      COLOR="yellow";
    elif [[ $LEVEL == 'INFORMATION' ]]; then
      COLOR="gray";
    elif [[ $LEVEL == 'NOT CLASSIFIED' ]]; then
      COLOR="gray";
    fi
  # nagios levels
  elif [[ $LEVEL == 'CRITICAL' ]]; then
    COLOR="red";
  elif [[ $LEVEL == 'WARNING' ]]; then
    COLOR="yellow";
  elif [[ $LEVEL == 'UNKNOWN' ]]; then
    COLOR="gray";
  elif [[ $LEVEL == 'OK' ]]; then
    COLOR="green";
  elif [[ $LEVEL == 'DOWN' ]]; then
    COLOR="red";
  elif [[ $LEVEL == 'UP' ]]; then
    COLOR="green";
  fi
fi

if [ -z "$INPUT" ]; then
  # read stdin
  INPUT=$(cat)
fi

# replace newlines with XHTML <br>
if [ $FORMAT == 'html' ]; then
    INPUT=$(echo -n "${INPUT}" | sed "s/$/\<br\>/")
fi

# replace bare URLs with real hyperlinks
INPUT=$(echo -n "${INPUT}" | perl -p -e "s/(?<!href=\"|href=')((?:https?|ftp|mailto)\:\/\/[^ \n]*)/\<a href=\"\1\"\>\1\<\/a>/g")

# urlencode with perl
if [ $API == 'v1' ]; then
  INPUT=$(echo -n "${INPUT}" | perl -p -e 's/([^A-Za-z0-9])/sprintf("%%%02X", ord($1))/seg')
fi

# replace notification boolean from 1/0 to 'true'/'false' for API v2
if [ $API == 'v2' ]; then
  if [ $NOTIFY -eq 0 ]; then
    NOTIFY='false'
  else
    NOTIFY='true'
  fi
fi

# do the curl
if [ $API == 'v2' ]; then
  curl -sS \
    -H 'Content-type: application/json' \
    -d "{\"color\":\"$COLOR\", \"message\":\"$INPUT\", \"message_format\":\"$FORMAT\", \"notify\":$NOTIFY}" \
    https://$HOST/v2/room/$ROOM_ID/notification?auth_token=$TOKEN
else
  curl -sS \
    -d "auth_token=$TOKEN&room_id=$ROOM_ID&from=$FROM&color=$COLOR&message_format=$FORMAT&message=$INPUT&notify=$NOTIFY" \
    https://$HOST/v1/rooms/message
fi
